CREATE TABLE drivers (
    id VARCHAR(80) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(40) DEFAULT '',
    title VARCHAR(80) DEFAULT 'Driver',
    active BOOLEAN DEFAULT TRUE,
    work_days TEXT DEFAULT 'mon,tue,wed,thu,fri'
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    driver_id VARCHAR(80) UNIQUE REFERENCES drivers(id)
);

CREATE TABLE patients (
    id VARCHAR(80) PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    dob VARCHAR(20) DEFAULT '',
    phone VARCHAR(40) DEFAULT '',
    address TEXT DEFAULT '',
    mobility VARCHAR(80) DEFAULT '',
    chair_width INTEGER,
    vehicle_requirement VARCHAR(40) DEFAULT '',
    notes TEXT DEFAULT ''
);

CREATE TABLE appointments (
    id VARCHAR(100) PRIMARY KEY,
    patient_id VARCHAR(80) NOT NULL REFERENCES patients(id),
    date VARCHAR(20) NOT NULL,
    medical_appointment_time VARCHAR(10) DEFAULT '',
    appointment_type VARCHAR(80) DEFAULT 'Doctor Appointment',
    notes TEXT DEFAULT '',
    one_way BOOLEAN DEFAULT FALSE
);
CREATE INDEX ix_appointments_date ON appointments(date);

CREATE TABLE trips (
    id VARCHAR(120) PRIMARY KEY,
    appointment_id VARCHAR(100) NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
    direction VARCHAR(120) NOT NULL,
    pickup_time VARCHAR(10) DEFAULT '',
    driver_id VARCHAR(80) REFERENCES drivers(id),
    duration_minutes INTEGER DEFAULT 45,
    pickup_address TEXT DEFAULT '',
    destination TEXT DEFAULT '',
    status VARCHAR(30) DEFAULT 'not-ready',
    notes TEXT DEFAULT '',
    trip_order INTEGER DEFAULT 0
);
CREATE INDEX ix_trips_driver_time ON trips(driver_id, pickup_time);
